module.exports = [
  'https://storage.googleapis.com/phone-catalog/apple-iphone-11.jpg',
  'https://storage.googleapis.com/phone-catalog/apple-iphone-7r4.jpg',
  'https://storage.googleapis.com/phone-catalog/apple-iphone-8-new.jpg',
  'https://storage.googleapis.com/phone-catalog/samsung-galaxy-a01.jpg',
  'https://storage.googleapis.com/phone-catalog/samsung-galaxy-a12-sm-a125.jpg',
  'https://storage.googleapis.com/phone-catalog/samsung-galaxy-a20.jpg',
  'https://storage.googleapis.com/phone-catalog/samsung-galaxy-a21s-.jpg',
  'https://storage.googleapis.com/phone-catalog/samsung-galaxy-a71.jpg',
  'https://storage.googleapis.com/phone-catalog/samsung-galaxy-j5-sm-j500f.jpg',
  'https://storage.googleapis.com/phone-catalog/samsung-galaxy-j7-prime.jpg',
  'https://storage.googleapis.com/phone-catalog/samsung-galaxy-note20-ultra-.jpg',
  'https://storage.googleapis.com/phone-catalog/samsung-galaxy-note9-r1.jpg',
  'https://storage.googleapis.com/phone-catalog/samsung-galaxy-s10-plus-new.jpg',
  'https://storage.googleapis.com/phone-catalog/samsung-galaxy-s21-ultra-5g-.jpg',
  'https://storage.googleapis.com/phone-catalog/samsung-galaxy-s9-.jpg',
];
